SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF SCHEMA_ID(N'etl') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA etl AUTHORIZATION dbo;');
END;
GO

IF SCHEMA_ID(N'dw') IS NULL
BEGIN
    EXEC(N'CREATE SCHEMA dw AUTHORIZATION dbo;');
END;
GO